# Generated by Django 5.1.4 on 2025-06-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoupload',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='videoupload',
            name='video',
        ),
        migrations.AddField(
            model_name='videoupload',
            name='video_url',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='result',
            field=models.CharField(blank=True, default='Pending', max_length=100),
        ),
    ]
