# Generated by Django 5.1.4 on 2025-06-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance_app', '0003_videoupload_processed_video_alter_videoupload_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='video_url',
            field=models.URLField(),
        ),
    ]
